#!/usr/bin/env python3
"""
fractal_complete.py — Auto-Complete The Fractal Architecture

Scans every directory in the workspace and generates minimal-but-correct
navigation trinity files (MANIFEST.md, CLAUDE.md, CONTEXT.md) wherever
they are missing.

This is the "self-shaping" part of the architecture: the workspace can
examine its own structural gaps and fill them in so agents always have
complete navigation context at every depth level.

Usage:
    python fractal_complete.py              # dry run — shows what would be created
    python fractal_complete.py --apply      # actually writes the missing files
    python fractal_complete.py --apply --only manifest   # only missing MANIFESTs
"""

import sys
import argparse
from pathlib import Path
from datetime import datetime, timezone

SKIP_DIRS = {
    "__pycache__", ".git", "node_modules", ".pytest_cache",
    ".mypy_cache", ".venv", "venv", ".tox", "output",
}

WORKSPACE_ROOT_DEFAULT = str(Path(__file__).parent.parent.parent)


# ──────────────────────────────────────────────────────────────────────────────
# TEMPLATE GENERATORS
# Each returns a string — the file content to write.
# ──────────────────────────────────────────────────────────────────────────────

def _infer_type(rel: str) -> str:
    """Infer the directory type from its position in the tree."""
    parts = Path(rel).parts
    if not parts:
        return "workspace"
    if "_meta" in parts:   return "meta-infrastructure"
    if "_core" in parts:   return "core-conventions"
    if "programs" in parts and len(parts) >= 2:
        idx = list(parts).index("programs")
        if len(parts) == idx + 1:  return "program-registry"
        if len(parts) == idx + 2:  return "program"
        return "program-submodule"
    if "_planning" in parts: return "planning"
    if "_intake" in parts:   return "intake"
    if "_registry" in parts: return "registry"
    if "shared" in parts:    return "shared-contracts"
    if "gaps" in parts:      return "gap-registry"
    return "module"


def _infer_status(dirpath: Path) -> str:
    """Guess status from existing content."""
    files = {f.name for f in dirpath.iterdir() if f.is_file()} if dirpath.exists() else set()
    subdirs = [f for f in dirpath.iterdir() if f.is_dir()] if dirpath.exists() else []
    if any(f.endswith(".py") or f.endswith(".ts") for f in files):
        return "active"
    if subdirs:
        return "scaffold"
    return "scaffold"


def gen_manifest(dirpath: Path, rel: str) -> str:
    """Generate a MANIFEST.md for the given directory."""
    name    = dirpath.name
    dtype   = _infer_type(rel)
    status  = _infer_status(dirpath)
    ts      = datetime.now(timezone.utc).isoformat(timespec="seconds")
    depth   = len(Path(rel).parts)

    # Collect children for the contents section
    children = []
    if dirpath.exists():
        for item in sorted(dirpath.iterdir()):
            if item.name in SKIP_DIRS or item.name.startswith('.'):
                continue
            kind = "directory" if item.is_dir() else "file"
            children.append(f"  - `{item.name}` ({kind})")
    children_block = "\n".join(children) if children else "  - (empty)"

    return f"""# MANIFEST — {name}

<!-- auto-generated by fractal_complete.py · {ts} -->
<!-- Update this file as the directory evolves. -->

## Envelope

| Field       | Value                    |
|-------------|--------------------------|
| name        | {name}                   |
| type        | {dtype}                  |
| depth       | {depth}                  |
| status      | {status}                 |
| path        | {rel}                    |

## Purpose

<!-- TODO: Describe what this directory is and why it exists. -->
{name} — {dtype}.

## Contents

{children_block}

## Needs

<!-- TODO: List what this directory depends on from outside itself. -->
- (to be defined)

## Returns

<!-- TODO: List what this directory produces for the rest of the workspace. -->
- (to be defined)

## Gap Status

- open: none
- closed: none
"""


def gen_claude(dirpath: Path, rel: str) -> str:
    """Generate a CLAUDE.md for the given directory (depth-1 map)."""
    name = dirpath.name
    ts   = datetime.now(timezone.utc).isoformat(timespec="seconds")

    # List immediate subdirectories for the map
    subdirs = []
    if dirpath.exists():
        for item in sorted(dirpath.iterdir()):
            if item.is_dir() and item.name not in SKIP_DIRS and not item.name.startswith('.'):
                subdirs.append(f"| `{item.name}/` | <!-- one-line purpose → fill in --> |")
    map_block = "\n".join(subdirs) if subdirs else "| (no subdirectories) | — |"

    return f"""# CLAUDE.md — {name}

<!-- auto-generated by fractal_complete.py · {ts} -->
<!-- This file is ALWAYS loaded. Keep it to depth-1 only: names + one-line purposes. -->
<!-- Never include implementation details here — put those in CONTEXT.md or MANIFEST.md. -->

## What Is In This Directory

| Name | Purpose |
|------|---------|
{map_block}

## Quick Rules For This Directory

<!-- TODO: Add any directory-specific rules agents must follow here. -->
- Follow patterns in `_core/CONVENTIONS.md`
- Log every inference to `_meta/gaps/pending.txt`

## Cross-References

<!-- TODO: List dependencies on other parts of the workspace. -->
- (none defined yet)
"""


def gen_context(dirpath: Path, rel: str) -> str:
    """Generate a CONTEXT.md for the given directory (task router)."""
    name = dirpath.name
    ts   = datetime.now(timezone.utc).isoformat(timespec="seconds")

    subdirs = []
    if dirpath.exists():
        for item in sorted(dirpath.iterdir()):
            if item.is_dir() and item.name not in SKIP_DIRS and not item.name.startswith('.'):
                subdirs.append(
                    f"| <!-- task type --> | `{item.name}/` | <!-- what to do there --> |"
                )
    routing = "\n".join(subdirs) if subdirs else "| (define task types) | (define destination) | (define action) |"

    return f"""# CONTEXT.md — {name}

<!-- auto-generated by fractal_complete.py · {ts} -->
<!-- This is the task router. Agents read this to know WHERE to go for a given task. -->
<!-- Keep it focused: task type → location → what to do. -->

## Task Routing

| If your task is… | Go to | Do |
|-----------------|-------|----|
{routing}

## Active Work

<!-- TODO: List what is currently in progress in this directory. -->
- (to be defined)

## Fix-First Rule

If you find a broken file, incorrect data, or missing required content:
fix it immediately before starting your primary task.

## Inference Logging

Any time you derive something not written in a file, log it immediately:
`[ISO-8601] | {rel} | [filename consulted] | inferred "[what you inferred]"`
→ write to `_meta/gaps/pending.txt`
"""


# ──────────────────────────────────────────────────────────────────────────────
# SCANNER
# ──────────────────────────────────────────────────────────────────────────────

def scan(root: Path) -> list[dict]:
    """Return list of gaps: dirs missing one or more trinity files."""
    gaps = []
    for dirpath in sorted(root.rglob("*")):
        try:
            if not dirpath.is_dir():
                continue
        except OSError:
            continue
        if any(part in SKIP_DIRS or part.startswith('.') for part in dirpath.parts):
            continue
        try:
            rel = dirpath.relative_to(root).as_posix()
        except ValueError:
            continue

        contents    = list(dirpath.iterdir()) if dirpath.exists() else []
        file_names  = {f.name for f in contents if f.is_file()}
        child_dirs  = [f for f in contents if f.is_dir() and f.name not in SKIP_DIRS]

        # Only check routing-relevant dirs (have children, or shallow ≤ depth 2)
        depth = len(Path(rel).parts)
        if not child_dirs and depth > 2:
            continue

        missing = []
        if "MANIFEST.md" not in file_names:
            missing.append("MANIFEST.md")
        if "CLAUDE.md" not in file_names:
            missing.append("CLAUDE.md")
        if "CONTEXT.md" not in file_names:
            missing.append("CONTEXT.md")

        if missing:
            gaps.append({"path": dirpath, "rel": rel, "missing": missing})

    return gaps


# ──────────────────────────────────────────────────────────────────────────────
# MAIN
# ──────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Auto-complete fractal navigation trinity")
    parser.add_argument("root", nargs="?", default=WORKSPACE_ROOT_DEFAULT,
                        help="Workspace root")
    parser.add_argument("--apply", action="store_true",
                        help="Actually write the files (default: dry run)")
    parser.add_argument("--only", choices=["manifest", "claude", "context"],
                        help="Only generate this file type")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    if not root.exists():
        print(f"ERROR: {root} does not exist", file=sys.stderr)
        sys.exit(1)

    mode = "DRY RUN" if not args.apply else "APPLY"
    print(f"\n[fractal_complete] root={root}")
    print(f"[fractal_complete] mode={mode}\n")

    gaps   = scan(root)
    target = args.only  # None means all

    created = 0
    for gap in gaps:
        dirpath = gap["path"]
        rel     = gap["rel"]
        missing = gap["missing"]

        for fname in missing:
            ftype = fname.replace(".md", "").lower()   # manifest | claude | context
            if target and ftype != target:
                continue

            dest = dirpath / fname
            if target == "manifest" or fname == "MANIFEST.md":
                content = gen_manifest(dirpath, rel)
            elif fname == "CLAUDE.md":
                content = gen_claude(dirpath, rel)
            else:
                content = gen_context(dirpath, rel)

            if args.apply:
                dest.write_text(content, encoding="utf-8")
                print(f"  CREATED  {rel}/{fname}")
            else:
                print(f"  MISSING  {rel}/{fname}")
            created += 1

    print(f"\n[fractal_complete] {'Created' if args.apply else 'Would create'} {created} file(s).")
    if not args.apply and created > 0:
        print("[fractal_complete] Run with --apply to generate them.")


if __name__ == "__main__":
    main()
